### ISSUE TITLE
Baseline mAP@.5 performance?

### ISSUE THREAD

**Issue by Karol-G** [node21challenge/node21_detection_baseline#1]
Hi,

what is the mAP@.5 performance of the used Faster R-CNN baseline?

Best
Karol-G

**Comment by keelinm** [comment]
Hi,
You can find this on the node21 site at https://node21.grand-challenge.org/evaluation/challenge/leaderboard/ (you need to click on "show all metrics").  It is 0.5323 .  
Best, 
Keelin

**Comment by Karol-G** [comment]
Hi, 
thanks for the reply! I don't see mAP@.5 there if I click on "show all metrics". Does 'S (0.5 FP)' correspond to the mAP@.5 performance as it has the value of 0.5323? And if yes why is it called differently and what does it stand for?

Best
Karol

**Comment by ecemlago** [comment]
Hi Karol, 

Sorry for the late answer. We check the forum every day and answer the questions regarding the challenge, so it would be better if you post this type of question to the forum rather than here. (of course, if there is an issue in the baseline code, please post it here :) )

No, we do not calculate mAP@.5, we calculate average sensitivity at different average FP rates. (0.5,0.25 etc, per image). Please see the [details](https://node21.grand-challenge.org/Details/) page, there is a section where we explain the evaluation metrics which are calculated for this challenge.

Best, Ecem
